seed: 1234
dataset: "planning-datasets/data/mpd/mazes_032_moore_c8"
logdir: "model"
encoder: "CNN"  # either CNN or Unet
Tmax: 0.25

params:
  batch_size: 100
  num_epochs: 50
  lr: 0.001


hydra:
  job:
    chdir: False
